set_property IOSTANDARD LVCMOS33 [get_ports {rgb_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_led[0]}]
set_property PACKAGE_PIN V16 [get_ports {rgb_led[2]}]
set_property PACKAGE_PIN F17 [get_ports {rgb_led[1]}]
set_property PACKAGE_PIN M17 [get_ports {rgb_led[0]}]
set_property PACKAGE_PIN T16 [get_ports {x[3]}]
set_property PACKAGE_PIN W13 [get_ports {x[2]}]
set_property PACKAGE_PIN P15 [get_ports {x[1]}]
set_property PACKAGE_PIN G15 [get_ports {x[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y[0]}]
set_property PACKAGE_PIN D18 [get_ports {y[3]}]
set_property PACKAGE_PIN G14 [get_ports {y[2]}]
set_property PACKAGE_PIN M15 [get_ports {y[1]}]
set_property PACKAGE_PIN M14 [get_ports {y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN K17 [get_ports clk]
create_clock -add -name sys_clk_pin -period 8.00 -waveform {0 4} [get_ports { clk }];
set_property PACKAGE_PIN K19 [get_ports minor]
set_property PACKAGE_PIN Y16 [get_ports plus]
set_property PACKAGE_PIN P16 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports minor]
set_property IOSTANDARD LVCMOS33 [get_ports plus]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_false_path -from [get_ports plus]
set_false_path -from [get_ports minor]
set_false_path -from [get_ports reset]
set_false_path -to [get_ports {rgb_led[*]}]
set_false_path -to [get_ports {y[*]}]
set_false_path -from [get_ports {x[*]}]
